require("nvim-treesitter.configs").setup {
  ensure_installed = {
    "lua",
    "vim",
    "vimdoc",
    "c",
    "cmake",
    "css",
    "dockerfile",
    "gitignore",
    "go",
    "graphql",
    "html",
    "java",
    "javascript",
    "json",
    -- "latex",
    "markdown",
    "markdown_inline",
    "nginx",
    "php",
    "proto",
    "python",
    "scss",
    "sql",
    "tsx",
    "typescript",
    "vue",
    "xml",
    "yaml",
  },
  highlight = { enable = true },
  autotag = { enable = true },
}
